on:
  push:
    branches: [ "32-move-to-production" ]

name: Build & Deploy to Production
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install
      run: npm ci
    - name: Build
      env: 
        VITE_EMBEDDED_MAP: '${{ secrets.VITE_EMBEDDED_MAP }}'
      run: npm run build
    - name: Store production build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist/
    - name: Store release notes
      uses: actions/upload-artifact@v3
      with:
        name: notes
        path: ./ReleaseNotes.md
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Recover production build
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: ./dist/
    - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 91.142.223.178
        username: teraac.com
        password: ${{ secrets.ftp_password_prod }}
        local-dir: ./dist/
        server-dir: ./httpdocs/
  email:
    needs: deploy
    name: Email
    runs-on: ubuntu-latest
    steps:
    - name: Recover release notes
      uses: actions/download-artifact@v3
      with:
        name: notes
        path: ./
    - name: Read release notes
      id: read-file
      uses: juliangruber/read-file-action@v1.1.6
      with:
        path: ./ReleaseNotes.md
    - uses: dawidd6/action-send-mail@v3.7.1
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MY_EMAIL }}
        password: ${{ secrets.MY_EMAIL_PASSWORD }}
        subject: Nova versió de la web (PUBLICA)
        from: xcarolr@gmail.com
        body: |
          Bones!

          Hi ha una versió de la web pública: www.teraac.com
          
          Salutacions!
        to: xcarolr@gmail.com
