on:
  push:
    branches: [ "test/**" ]

name: Build & Deploy to Stage
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install
      run: npm ci
    - name: Build
      env: 
        VITE_EMBEDDED_MAP: '${{ secrets.VITE_EMBEDDED_MAP }}'
      run: npm run build
    - name: Store htaccess
      run: cp ./server/.htaccess ./dist/
    - name: Store production build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist/
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Recover production build
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: ./dist/
    - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.xicra.com
        username: teraac
        password: ${{ secrets.ftp_password }}
        local-dir: ./dist/
